### PR TITLE
Add a mouse.dispose() function to remove event listeners

### LINKED ISSUE #2: Currently no way to remove listener
just FYI

### PR DESCRIPTION
**Pull request by pconerly**
Resolves #2

### CODE REVIEW

**Comment by flekschas** [comment]
@hughsk Any plans on merging this? :)

**Comment by hackergrrl** [comment]
@hughsk I'm happy to maintain this module if you want it taken off your plate.  o/

**Comment by hughsk** [comment]
@noffle thanks! Have added you and @pconerly to the repo and package. If there are any other packages you would like access to lmk :)

**Comment by hackergrrl** [comment]
@hughsk Could you grant me npm permissions too? I wasn't added.

**Comment by hughsk** [comment]
Oh oops -- done!

**Comment by hackergrrl** [comment]
Thanks.

2.1.0

**Pull request merged**
